CREATE TABLE CLIENTS
(
	ID                  NUMBER(10) NOT NULL,
	NAME                VARCHAR(1000) NOT NULL,
	PLACE_OF_BIRTH      VARCHAR(1000) NOT NULL,
	DATE_OF_BIRTH       DATE NOT NULL,
	ADDRESS             VARCHAR(255) NOT NULL,
	PASSPORT            VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE TARIFS
(
	ID                  NUMBER(10) NOT NULL,
	NAME                VARCHAR(100) NOT NULL,
	COST                NUMBER(10.2) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE PRODUCT_TYPE
(
	ID                  NUMBER(10) NOT NULL,
	TARIF_REF           NUMBER(10) NOT NULL,
	NAME                VARCHAR(100) NOT NULL,
	BEGIN_DATE          DATE NOT NULL,
	END_DATE            DATE NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (TARIF_REF) REFERENCES TARIFS (ID) ON DELETE CASCADE
);
CREATE TABLE PRODUCTS
(
	ID                  NUMBER(10) NOT NULL,
	PRODUCT_TYPE_ID     NUMBER(10) NOT NULL,
	CLIENT_REF          NUMBER(10) NOT NULL,
	NAME                VARCHAR(100) NOT NULL,
	OPEN_DATE           DATE NOT NULL,
	CLOSE_DATE          DATE NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLIENT_REF) REFERENCES CLIENTS (ID) ON DELETE CASCADE,
	FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (ID) ON DELETE CASCADE
);
CREATE TABLE ACCOUNTS
(
	ID                  NUMBER(10) NOT NULL,
	CLIENT_REF          NUMBER(10) NOT NULL,
	PRODUCT_REF         NUMBER(10) NOT NULL,
	NAME                VARCHAR(100) NOT NULL,
	SALDO               NUMBER(10.2) NOT NULL,
	OPEN_DATE           DATE NOT NULL,
	CLOSE_DATE          DATE NULL,
	ACC_NUM             VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLIENT_REF) REFERENCES CLIENT (ID) ON DELETE CASCADE,
	FOREIGN KEY (PRODUCT_REF) REFERENCES PRODUCT (ID) ON DELETE CASCADE
);
CREATE TABLE RECORDS
(
	ID                  NUMBER(10) NOT NULL,
	ACC_REF             NUMBER(10) NOT NULL,
	DT                  NUMBER(1) NOT NULL,
	SUM                 NUMBER(10.2) NOT NULL,
	OPER_DATE           DATE NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ACC_REF) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);
