UPDATE PRODUCTS
SET CLOSE_DATE = datetime('now')
WHERE (SELECT
    sum(power(-1, RECORDS.DT)*RECORDS.SUM)
    FROM ACCOUNTS
	JOIN RECORDS on RECORDS.ACC_REF = ACCOUNTS.ID
    WHERE ACCOUNTS.PRODUCT_REF = PRODUCTS.ID
) = 0